services:
  frontend:
    build: ./frontend
    image: lounge-books-frontend
    volumes:
      - ./frontend:/app
      - front_node_modules:/app/node_modules
    ports:
      - 5173:5173

  backend:
    build: ./backend
    image: lounge-books-backend
    ports:
      - 8080:8080

volumes:
  front_node_modules:
