services:
  frontend:
    build: ./frontend
    image: lounge-books-frontend
    volumes:
      - ./frontend:/app
      - front_node_modules:/app/node_modules
    ports:
      - 5173:5173

  backend:
    build: ./backend
    image: lounge-books-backend
    environment:
      - APP_PORT=8080
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DRIVER=postgres
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    depends_on:
      - postgres
    ports:
      - 8080:8080

  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    restart: always
    ports:
      - 5432:5432

volumes:
  front_node_modules: